# -*- coding: utf-8 -*-
"""Confusion_X4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jJVIFhYtwXgvwb2i2J7ltJWLOhq9cuOB
"""

from google.colab import drive
drive.mount('/content/gdrive')

from pickle import load,dump
from copy import deepcopy

f1=open("/content/gdrive/My Drive/Colab Notebooks/vaderxsenti.pickle","rb")
buff=load(f1)

vader=load(f1)
senti=load(f1)

f1.close()

f1=open("/content/gdrive/My Drive/Colab Notebooks/Post_140.pickle","rb")
s140=load(f1)

f1.close()

f1=open("/content/gdrive/My Drive/Colab Notebooks/Post_textblob.pickle","rb")
tblob=load(f1)

f1.close()

"""Confusion Matrix : Vader and SentiStrength"""

con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

vadxsenti={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

c_vs=0

for i in vader:
  if i in senti:
    c_vs+=1
    for j in ["tweet_text","snowball","porter"]:
      #Selective update of matrix
      if senti[i]=='neg':
        if vader[i][j]=='neg':
          vadxsenti[j]["g1g2"]+=1
        elif vader[i][j]=='neu':
          vadxsenti[j]["u1g2"]+=1
        else:
          vadxsenti[j]["p1g2"]+=1
      elif senti[i]=='neu':
        if vader[i][j]=='neg':
          vadxsenti[j]["g1u2"]+=1
        elif vader[i][j]=='neu':
          vadxsenti[j]["u1u2"]+=1
        else:
          vadxsenti[j]["p1u2"]+=1
      else:
        if vader[i][j]=='neg':
          vadxsenti[j]["g1p2"]+=1
        elif vader[i][j]=="neu":
          vadxsenti[j]["u1p2"]+=1
        else:
          vadxsenti[j]["p1p2"]+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("SentiStrength\t"+k[0],end="\t")
    for p in k[1:]:
      print(vadxsenti[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("SentiStrength\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(vadxsenti[j][p]*100/c_vs,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(vadxsenti[j]["p1p2"]+vadxsenti[j]["g1g2"]+vadxsenti[j]["u1u2"],end="\t")
  print(round((vadxsenti[j]["p1p2"]+vadxsenti[j]["g1g2"]+vadxsenti[j]["u1u2"])*100/c_vs,2),"%")

c_vs

"""Confusion Matrix : Vader and Sentiment140"""



con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

vadxs140={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

c_v140=0

for i in vader:
  if i in s140:
    c_v140+=1
    for j in ["tweet_text","snowball","porter"]:
      #Selective update of matrix
      if s140[i][j]=='neg':
        if vader[i][j]=='neg':
          vadxs140[j]["g1g2"]+=1
        elif vader[i][j]=='neu':
          vadxs140[j]["u1g2"]+=1
        else:
          vadxs140[j]["p1g2"]+=1
      elif s140[i][j]=='neu':
        if vader[i][j]=='neg':
          vadxs140[j]["g1u2"]+=1
        elif vader[i][j]=='neu':
          vadxs140[j]["u1u2"]+=1
        else:
          vadxs140[j]["p1u2"]+=1
      else:
        if vader[i][j]=='neg':
          vadxs140[j]["g1p2"]+=1
        elif vader[i][j]=="neu":
          vadxs140[j]["u1p2"]+=1
        else:
          vadxs140[j]["p1p2"]+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("Sentiment140\t"+k[0],end="\t")
    for p in k[1:]:
      print(vadxs140[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("Sentiment140\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(vadxs140[j][p]*100/c_v140,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(vadxs140[j]["p1p2"]+vadxs140[j]["g1g2"]+vadxs140[j]["u1u2"],end="\t")
  print(round((vadxs140[j]["p1p2"]+vadxs140[j]["g1g2"]+vadxs140[j]["u1u2"])*100/c_v140,2),"%")

"""Confusion Matrix : VADER and TextBlob"""

con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

vadxtext={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

c_vt=0

for i in vader:
  if i in tblob:
    c_vt+=1
    for j in ["tweet_text","snowball","porter"]:
      #Selective update of matrix
      if tblob[i][j]=='neg':
        if vader[i][j]=='neg':
          vadxtext[j]["g1g2"]+=1
        elif vader[i][j]=='neu':
          vadxtext[j]["u1g2"]+=1
        else:
          vadxtext[j]["p1g2"]+=1
      elif tblob[i][j]=='neu':
        if vader[i][j]=='neg':
          vadxtext[j]["g1u2"]+=1
        elif vader[i][j]=='neu':
          vadxtext[j]["u1u2"]+=1
        else:
          vadxtext[j]["p1u2"]+=1
      else:
        if vader[i][j]=='neg':
          vadxtext[j]["g1p2"]+=1
        elif vader[i][j]=="neu":
          vadxtext[j]["u1p2"]+=1
        else:
          vadxtext[j]["p1p2"]+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("TextBlob\t"+k[0],end="\t")
    for p in k[1:]:
      print(vadxs140[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("TextBlob\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(vadxtext[j][p]*100/c_v140,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(vadxtext[j]["p1p2"]+vadxtext[j]["g1g2"]+vadxtext[j]["u1u2"],end="\t")
  print(round((vadxtext[j]["p1p2"]+vadxtext[j]["g1g2"]+vadxtext[j]["u1u2"])*100/c_vt,2),"%")

"""Confusion Matrix : Sentiment140 and SentiStrength"""

con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

s140xsenti={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

c_ss=0

for i in s140:
  if i in senti:
    c_ss+=1
    for j in ["tweet_text","snowball","porter"]:
      #Selective update of matrix
      if senti[i]=='neg':
        if s140[i][j]=='neg':
          s140xsenti[j]["g1g2"]+=1
        elif s140[i][j]=='neu':
          s140xsenti[j]["u1g2"]+=1
        else:
          s140xsenti[j]["p1g2"]+=1
      elif senti[i]=='neu':
        if s140[i][j]=='neg':
          s140xsenti[j]["g1u2"]+=1
        elif s140[i][j]=='neu':
          s140xsenti[j]["u1u2"]+=1
        else:
          s140xsenti[j]["p1u2"]+=1
      else:
        if s140[i][j]=='neg':
          s140xsenti[j]["g1p2"]+=1
        elif s140[i][j]=="neu":
          s140xsenti[j]["u1p2"]+=1
        else:
          s140xsenti[j]["p1p2"]+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tSentiment140")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("SentiStrength\t"+k[0],end="\t")
    for p in k[1:]:
      print(s140xsenti[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tSentiment140")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("SentiStrength\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(s140xsenti[j][p]*100/c_ss,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(s140xsenti[j]["p1p2"]+s140xsenti[j]["g1g2"]+s140xsenti[j]["u1u2"],end="\t")
  print(round((s140xsenti[j]["p1p2"]+s140xsenti[j]["g1g2"]+s140xsenti[j]["u1u2"])*100/c_ss,2),"%")

"""Confusion Matrix : TextBlob and SentiStrength"""

con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

textxsenti={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

c_ts=0

for i in tblob:
  if i in senti:
    c_ts+=1
    for j in ["tweet_text","snowball","porter"]:
      #Selective update of matrix
      if senti[i]=='neg':
        if tblob[i][j]=='neg':
          textxsenti[j]["g1g2"]+=1
        elif tblob[i][j]=='neu':
          textxsenti[j]["u1g2"]+=1
        else:
          textxsenti[j]["p1g2"]+=1
      elif senti[i]=='neu':
        if tblob[i][j]=='neg':
          textxsenti[j]["g1u2"]+=1
        elif tblob[i][j]=='neu':
          textxsenti[j]["u1u2"]+=1
        else:
          textxsenti[j]["p1u2"]+=1
      else:
        if tblob[i][j]=='neg':
          textxsenti[j]["g1p2"]+=1
        elif tblob[i][j]=="neu":
          textxsenti[j]["u1p2"]+=1
        else:
          textxsenti[j]["p1p2"]+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tTextBlob")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("SentiStrength\t"+k[0],end="\t")
    for p in k[1:]:
      print(textxsenti[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tTextBlob")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("SentiStrength\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(textxsenti[j][p]*100/c_ts,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(textxsenti[j]["p1p2"]+textxsenti[j]["g1g2"]+textxsenti[j]["u1u2"],end="\t")
  print(round((textxsenti[j]["p1p2"]+textxsenti[j]["g1g2"]+textxsenti[j]["u1u2"])*100/c_ts,2),"%")

"""Confusion Matrix : Sentiment140 and TextBlob"""

con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

s140xtext={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

c_st=0

for i in s140:
  if i in tblob:
    c_st+=1
    for j in ["tweet_text","snowball","porter"]:
      #Selective update of matrix
      if tblob[i][j]=='neg':
        if s140[i][j]=='neg':
          s140xtext[j]["g1g2"]+=1
        elif s140[i][j]=='neu':
          s140xtext[j]["u1g2"]+=1
        else:
          s140xtext[j]["p1g2"]+=1
      elif tblob[i][j]=='neu':
        if s140[i][j]=='neg':
          s140xtext[j]["g1u2"]+=1
        elif s140[i][j]=='neu':
          s140xtext[j]["u1u2"]+=1
        else:
          s140xtext[j]["p1u2"]+=1
      else:
        if s140[i][j]=='neg':
          s140xtext[j]["g1p2"]+=1
        elif s140[i][j]=="neu":
          s140xtext[j]["u1p2"]+=1
        else:
          s140xtext[j]["p1p2"]+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tSentiment140")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("TextBlob\t"+k[0],end="\t")
    for p in k[1:]:
      print(s140xtext[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tSentiment140")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("TextBlob\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(s140xtext[j][p]*100/c_st,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(s140xtext[j]["p1p2"]+s140xtext[j]["g1g2"]+s140xtext[j]["u1u2"],end="\t")
  print(round((s140xtext[j]["p1p2"]+s140xtext[j]["g1g2"]+s140xtext[j]["u1u2"])*100/c_st,2),"%")

"""Confusion Matrix : Everything against Sentiment140"""

con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

tag_3x1={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

tdg_3x1={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

tag={
    "tweet_text":0,
     "snowball":0,
     "porter":0}


c_31=0

for i in senti:
  if i in vader and i in tblob and i in s140:
    c_31+=1
    for j in ["tweet_text","porter","snowball"]:

      if senti[i]==vader[i][j]==tblob[i][j]:
        tag[j]+=1
        if vader[i][j]=='neg':
          if s140[i][j]=='neg':
            tag_3x1[j]['g1g2']+=1
          elif s140[i][j]=='neu':
            tag_3x1[j]['u1g2']+=1
          else:
            tag_3x1[j]['p1g2']+=1
        elif vader[i][j]=='neu':
          if s140[i][j]=='neg':
            tag_3x1[j]['g1u2']+=1
          elif s140[i][j]=='neu':
            tag_3x1[j]['u1u2']+=1
          else:
            tag_3x1[j]['p1u2']+=1
        else:
          if s140[i][j]=='neg':
            tag_3x1[j]['g1p2']+=1
          elif s140[i][j]=='neu':
            tag_3x1[j]['u1p2']+=1
          else:
            tag_3x1[j]['p1p2']+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tSentiment140")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("Consolidated\t"+k[0],end="\t")
    for p in k[1:]:
      print(tag_3x1[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tSentiment140")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("Consolidated\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(tag_3x1[j][p]*100/c_31,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(tag_3x1[j]["p1p2"]+tag_3x1[j]["g1g2"]+tag_3x1[j]["u1u2"],end="\t")
  print(round((tag_3x1[j]["p1p2"]+tag_3x1[j]["g1g2"]+tag_3x1[j]["u1u2"])*100/c_31,2),"%")

"""Total Agreement Between VADER, SentiStrength and TextBlob"""

print("Total Agreement")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(tag[j],"\t",round(tag[j]*100/c_31,2),"%")

tag_3x1

tag

(28569+191778+218001)/1525049

790529/1525049

"""Custom Sentiment Check"""

nnff=open("/content/gdrive/My Drive/Colab Notebooks/CSA_V1_1_Results.pickle","rb")

csa={}

flag=0
ref=["tweet_text","snowball","porter"]

while 1:
  try:
    a=load(nnff)
    temp={}
    for i in ref:
      temp[i]=a[i]

    csa[a["tweet_id"]]=temp
  except EOFError:
    break

list(vader.keys())[0]
vader[1224071763761385472]
csa[1224071763761385472]

con_m={"g1g2":0, "u1g2":0, "p1g2":0,
       "g1u2":0, "u1u2":0, "p1u2":0,
       "g1p2":0, "u1p2":0, "p1p2":0}

vadxcsa={"tweet_text":deepcopy(con_m),
       "snowball":deepcopy(con_m),
       "porter":deepcopy(con_m)}

c_vcsa=0

for i in vader:
  if i in csa:
    c_vcsa+=1
    for j in ["tweet_text","snowball","porter"]:
      #Selective update of matrix
      if csa[i][j]=='neg':
        if vader[i][j]=='neg':
          vadxcsa[j]["g1g2"]+=1
        elif vader[i][j]=='neu':
          vadxcsa[j]["u1g2"]+=1
        else:
          vadxcsa[j]["p1g2"]+=1
      elif csa[i][j]=='neu':
        if vader[i][j]=='neg':
          vadxcsa[j]["g1u2"]+=1
        elif vader[i][j]=='neu':
          vadxcsa[j]["u1u2"]+=1
        else:
          vadxcsa[j]["p1u2"]+=1
      else:
        if vader[i][j]=='neg':
          vadxcsa[j]["g1p2"]+=1
        elif vader[i][j]=="neu":
          vadxcsa[j]["u1p2"]+=1
        else:
          vadxcsa[j]["p1p2"]+=1

lt=[("Neg","g1g2","u1g2","p1g2"),
    ("Neu","g1u2","u1u2","p1u2"),
    ("Pos","g1p2","u1p2","p1p2")]

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("CSA\t\t"+k[0],end="\t")
    for p in k[1:]:
      print(vadxcsa[j][p],end="\t")
    print()
  print()
  print()

print("\n\n")

for j in ["tweet_text","snowball","porter"]:
  print(j)
  print("\t\t\tVADER")
  print("\t\t\tNeg\tNeu\tPos")
  for k in lt:
    if k[0]!="Neu":
      print("\t\t"+k[0],end="\t")
    else:
      print("CSA\t\t"+k[0],end="\t")
    for p in k[1:]:
      print(str(round(vadxcsa[j][p]*100/c_vcsa,2))+"%",end="\t")
    print()
  print()
  print()

print("Total Agreement :")
for j in ["tweet_text","snowball","porter"]:
  print(j,end="\t")
  print(vadxcsa[j]["p1p2"]+vadxcsa[j]["g1g2"]+vadxcsa[j]["u1u2"],end="\t")
  print(round((vadxcsa[j]["p1p2"]+vadxcsa[j]["g1g2"]+vadxcsa[j]["u1u2"])*100/c_vcsa,2),"%")

"""Check CSA with VADER, SentiStrength and TextBlob"""

cvst_count=0
total_count_ch=0

for i in vader:
  if i in csa and i in senti and i in tblob:
    total_count_ch+=1

    if vader[i]["tweet_text"]==csa[i]["tweet_text"]==senti[i]==tblob[i]["tweet_text"]:
      cvst_count+=1

print(total_count_ch)
print(cvst_count)
print(cvst_count*100/total_count_ch)

"""Sunburst with VADER, SentiStrength and Textblob"""

lv_1={"pos":0,"neg":0, "neu":0}
lv_2={"pos":0,"neg":0, "neu":0}
lv_3={"pos":0,"neg":0, "neu":0}

#Level 1 VADER
#Level 2 SentiStrength
#Level 3 TextBlob

from copy import deepcopy

for i in vader:
  if i in senti and i in tblob:
    lv_1[vader[i]["tweet_text"]]+=1

for i in vader:
  if i in senti and i in tblob:
    if vader[i]["tweet_text"]==senti[i]:
      lv_2[senti[i]]+=1
    
for i in vader:
  if i in senti and i in tblob:
    if vader[i]["tweet_text"]==senti[i]==tblob[i]["tweet_text"]:
      lv_3[senti[i]]+=1

print(lv_1)
print(lv_2)
print(lv_3)

"""Including uClassify"""

uc_f=open("/content/gdrive/My Drive/Colab Notebooks/Post_uclassify.pickle","rb")
uc_dict=load(uc_f)

uvst_count=0
tot_uvst=0


for i in vader:
  if i in uc_dict and i in senti and i in tblob:
    tot_uvst+=1

    if vader[i]["tweet_text"]==uc_dict[i]["tweet_text"]==senti[i]==tblob[i]["tweet_text"]:
      uvst_count+=1





uvst_count

"""Getting list of tweet_ids for agreement between VADER, SentiStrength and TextBlob"""

#text_f=open("/content/gdrive/My Drive/Colab Notebooks/Agreement_id_text.txt","w")
#text_d_f=open("/content/gdrive/My Drive/Colab Notebooks/Disagreement_id_text.txt","w")
nnfff=open("/content/gdrive/My Drive/Colab Notebooks/a_dag.pickle","wb")
f11=open("/content/gdrive/My Drive/Colab Notebooks/H_23_0.pickle","rb")

req_list=load(f11)
l1,l2=[],[]
agree_text_count=0
dis_text_count=0
agree_text_tot=0

for i in req_list:
  if i in senti and i in tblob and i in vader:
    agree_text_tot+=1
    if vader[i]["tweet_text"]==senti[i]==tblob[i]["tweet_text"]:
      agree_text_count+=1
      l1.append((i,vader[i]["tweet_text"]))
      #text_f.write(str(i)+"\n")
    else:
      dis_text_count+=1
      #text_d_f.write(str(i)+"\n")
      l2.append(i)

dump(l1,nnfff)
dump(l2,nnfff)
nnfff.close()

agree_text_count*100/agree_text_tot
text_f.close()
text_d_f.close()

senti_hour={}

senti_file=open("/content/gdrive/My Drive/Colab Notebooks/Modified_Hourly_Slots.pickle","rb")
senti_dict=load(senti_file)

senti_dict.keys()

nnnfff=open("/content/gdrive/My Drive/Colab Notebooks/Post_treebankV2.pickle","rb")
tr_dict=load(nnnfff)

senti_hour={}

for i in senti_dict:
  temp={"pos":0,"neg":0,"neu":0}

  for j in senti_dict[i]:
    if j in csa:
      temp[csa[j]["tweet_text"]]+=1

  print(temp["pos"]+temp["neg"]+temp["neu"])
  senti_hour[i]=temp

tr_dict[1224071764038373379]

import pickle

senti_out=open("/content/gdrive/My Drive/Colab Notebooks/csa_mod_Sentiment_Hourly.pickle","wb")
pickle.dump(senti_hour,senti_out)
senti_out.close()

senti_hour={}

for i in senti_dict:
  temp={"pos":0,
        "neg":0,
        "neu":0}
  for j in senti_dict[i]:
    if j in vader and j in senti and j in tblob:
      if vader[j]["tweet_text"]==senti[j]==tblob[j]["tweet_text"]:
        temp[vader[j]["tweet_text"]]+=1
    else:
      pass
  
  print(temp["pos"]+temp["neg"]+temp["neu"])
  senti_hour[i]=temp

senti_hour["21:47"]

import pickle

senti_out=open("/content/gdrive/My Drive/Colab Notebooks/Agreement_Sentiment_Hourly.pickle","wb")
pickle.dump(senti_hour,senti_out)
senti_out.close()

senti_out=open("/content/gdrive/My Drive/Colab Notebooks/VADER_Sentiment_Hourly.txt","w")

for i in list(senti_hour.keys()):
  temp=i+"\n"
  for j in ["pos","neg","neu"]:
    temp+=(j+" :"+str(senti_hour[i][j])+"\t")
  senti_out.write(temp+"\n\n")

senti_out.close()

#tr_dict
#uc_dict
#csa
#senti
#tblob
#s140
#vader
#["tweet_text"]

count=0
for i in uc_dict:
  if i in vader and uc_dict[i]["tweet_text"]==vader[i]["tweet_text"]:
    count+=1

print(count)

from decimal import Decimal

qq=831093



print(round(Decimal(qq*100/1525050),2))